name: Maven CI/CD

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build plugin
      working-directory: ./helm-doc-maven-plugin
      run: mvn -B install --file pom.xml
      
    - name: Build plugin-test
      working-directory: ./helm-doc-maven-plugin-test
      run: mvn org.aurad:helm-doc-maven-plugin:0.0.1-SNAPSHOT:generate
