name: Maven CI/CD

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Cache the dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build plugin
      working-directory: ./helm-doc-maven-plugin
      run: mvn -B install --file pom.xml
      
    - name: Build plugin-test
      working-directory: ./helm-doc-maven-plugin-test
      run: mvn org.aurad:helm-doc-maven-plugin:0.0.1-SNAPSHOT:generate
    
    - name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: Abhi Auradkar
        author_email: aurabhi@yahoo.com
        message: "Generated Docs"
        add: "*.html"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  publish-job:
      runs-on: ubuntu-latest
      needs: [build_and_test]
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 8

        - name: Build plugin
          working-directory: ./helm-doc-maven-plugin
          run: mvn -B package --file pom.xml -DskipTests

        - name : Create staging dir and copy artifacts
          working-directory: ./helm-doc-maven-plugin
          run: pwd && mkdir ../staging && cp ./target/helm-doc-maven-plugin-*.jar ../staging && ls -ltr ../staging

        - uses: actions/upload-artifact@v2
          with:
            name: Package
            path: staging

