publish-job:
      runs-on: ubuntu-latest
      needs: [build_and_test]
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 8
        
        - name: Build plugin
          working-directory: ./helm-doc-maven-plugin
          run: mvn -B package --file pom.xml -DskipTests
          
        - name : Create staging dir and copy artifacts
          working-directory: ./helm-doc-maven-plugin
          run: mkdir staging && cp target/helm-doc-maven-plugin-*.jar staging
          
        - uses: actions/upload-artifact@v1
          with:
            name: Package
            path: staging
